mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: dev.itboot.mb.model
server:
  port: 5000

spring:
  datasource:
    # driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:localhost/test
    username: dbuser
    password: dbpass