# 共通
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: dev.itboot.mb.model
server:
  port: 5000

# 開発環境
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://awseb-e-xbuadehgum-stack-awsebrdsdatabase-erct3k0vxdno.crgmaiu24v2c.ap-northeast-1.rds.amazonaws.com:3306/ebdb
    username: admin
    password: hfymq322
  sql:
    init:
      mode: always